const express = require('express')
const router = express.Router()
const questions = require('./questions')
const hadithtypes = require('./hadithType')
const cardlists = require('./cardList')
const hadithlist = require('./hadithList')
const slider = require('./slider')
const auth = require('./auth')
const quizSet = require('./quizSet')
const quizResult = require('./quizResult')
const organization = require('./organization')
const tags = require('./tags')
const audioHadith = require('./audioHadith')
const islamicQuote = require('./islamicQuote')
const dua = require('./dua')
const adhkar = require('./adhkar')
const announcement = require('./announcement')
const scholar = require('./scholar')
const bookmark = require('./bookmark')

router.use('/questions', questions)
router.use('/hadith-type', hadithtypes)
router.use('/cardlists', cardlists)
router.use('/hadith-list', hadithlist)
router.use('/slider', slider)
router.use('/auth', auth)
router.use('/quiz-sets', quizSet)
router.use('/quiz-results', quizResult)
router.use('/organizations', organization)
router.use('/tags', tags)
router.use('/audio-hadiths', audioHadith)
router.use('/islamic-quotes', islamicQuote)
router.use('/duas', dua)
router.use('/adhkar', adhkar)
router.use('/announcements', announcement)
router.use('/scholars', scholar)
router.use('/bookmarks', bookmark)

module.exports = router
